name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build - ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        platform:
          - os-name: Linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            bin: dns-detector
            name: dns-detector-linux
          - os-name: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: dns-detector.exe
            name: dns-detector-windows-x86_64.exe
          - os-name: macOS-x86_64
            os: macos-latest
            target: x86_64-apple-darwin
            bin: dns-detector
            name: dns-detector-macos

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.target }}

      - name: Install musl-tools
        if: matrix.platform.target == 'x86_64-unknown-linux-musl'
        run: sudo apt-get install -y musl-tools

      - name: Build
        run: cargo build --release --target ${{ matrix.platform.target }}

      - name: Upload Binaries
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}
          name: ${{ matrix.platform.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
